services:
  server:
    image: node:latest
    volumes:
      - ./app/:/app/
    ports:
      - "8100:8100"
    depends_on:
      - db
    working_dir: /app/
    command:
      - bash
      - -c
      - "npm install && npm start"

